version: '3.4'

volumes:
  server-db-OasisData:
  celery-db-OasisData:

x-oasis-env: &oasis-env
  OASIS_ADMIN_USER: admin
  OASIS_ADMIN_PASS: password
  OASIS_DEBUG: ${DEBUG:-0}
  OASIS_RABBIT_HOST: rabbit
  OASIS_RABBIT_PORT: 5672
  OASIS_RABBIT_USER: rabbit
  OASIS_RABBIT_PASS: rabbit
  OASIS_SERVER_DB_HOST: server-db
  OASIS_SERVER_DB_PASS: oasis
  OASIS_SERVER_DB_USER: oasis
  OASIS_SERVER_DB_NAME: oasis
  OASIS_SERVER_DB_PORT: 5432
  OASIS_SERVER_DB_ENGINE: django.db.backends.postgresql
  OASIS_CELERY_DB_ENGINE: db+postgresql+psycopg
  OASIS_CELERY_DB_HOST: celery-db
  OASIS_CELERY_DB_PASS: password
  OASIS_CELERY_DB_USER: celery
  OASIS_CELERY_DB_NAME: celery
  OASIS_CELERY_DB_PORT: 5432
  STARTUP_RUN_MIGRATIONS: 'true'
  OASIS_STORAGE_TYPE: S3
  OASIS_AWS_BUCKET_NAME: example-bucket
  OASIS_AWS_S3_ENDPOINT_URL: "http://localstack-s3:4572"
  OASIS_AWS_ACCESS_KEY_ID: foobar
  OASIS_AWS_SECRET_ACCESS_KEY: foobar

services:
  localstack-s3:
    image: localstack-s3:latest
    build:
     context: .
     dockerfile: Dockerfile.localstack-s3
    ports:
      - "4567-4599:4567-4599" 

  server:
   restart: always
   image: ${SERVER_IMG:-coreoasis/api_server}:${SERVER_TAG:-latest}
   ports:
     - 8000:8000
   links:
     - server-db
     - celery-db
     - rabbit
   environment:
     <<: *oasis-env

  worker-monitor:
   restart: always
   image: ${SERVER_IMG:-coreoasis/api_server}:${SERVER_TAG:-latest}
   command: [wait-for-server, 'server:8000', celery, -A, src.server.oasisapi, worker, --loglevel=INFO]
   links:
     - server-db
     - celery-db
     - rabbit
   environment:
     <<: *oasis-env
  worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${WORKER_TAG:-latest}
    links:
     - celery-db
     - rabbit:myrabbit
    environment:
     <<: *oasis-env
     OASIS_MODEL_SUPPLIER_ID: OasisLMF
     OASIS_MODEL_ID: PiWind
     OASIS_MODEL_VERSION_ID: 1
     OASIS_MODEL_DATA_DIRECTORY: /home/worker/model
    volumes:
     - ../:/home/worker/model

  server-db:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: oasis
      POSTGRES_USER: oasis
      POSTGRES_PASSWORD: oasis
    volumes:
      - server-db-OasisData:/var/lib/postgresql/data:rw

  celery-db:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: celery
      POSTGRES_USER: celery
      POSTGRES_PASSWORD: password
    volumes:
      - celery-db-OasisData:/var/lib/postgresql/data:rw

  rabbit:
    restart: always
    image: rabbitmq:3.8.14-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - 5672:5672
      - 15672:15672
